[build]
    publish="dist"
    functions="functions"

[[redirects]]
    from="/api/*"
    to="/.netlify/functions/:splat"
    status=200
    force = true

[[redirects]]
    from="/*"
    to="/index.html"
    status=200
